[package]
name = "castor"
version = "0.1.0"
authors = ["Julien Blanchard <julien@sideburns.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "*"
gdk-pixbuf = "*"
gio = "*"
glib = "*"
glib-sys = "*"
pango = "*"
json = "*"
open = "*"
regex = "*"
native-tls = "*"
url = "*"
tempfile = "*"
dirs = "*"
lazy_static = "*"

[dependencies.gtk]
version = "0.8.0"
features = ["v3_16"]